In [171]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\mirii\desktop\fhkiel\programmierung\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\mirii\desktop\fhkiel\programmierung\.venv\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [172]:
import pandas as pd

# Nur die gewünschten Spalten einlesen
cols = ['TOURNR', 'LKW_KENNZ', 'FAHRERNAME', 'TOUR', 'ANKUNFT', 'ABFAHRT', 'GEOX', 'GEOY']

df_soll = pd.read_excel('CIS-Daten.xlsx', usecols=cols)

df_soll.head()

,TOURNR,LKW_KENNZ,FAHRERNAME,TOUR,ANKUNFT,ABFAHRT,GEOX,GEOY
0,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 06:00,02.03.2026 06:00,9.98632,53.52348
1,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 06:00,02.03.2026 06:30,9.98632,53.52348
2,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 06:49,02.03.2026 07:19,9.99383,53.54751
3,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 07:41,02.03.2026 08:11,9.98632,53.52348
4,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 08:31,02.03.2026 09:01,9.99383,53.54751

In [173]:
# Anzahl aller Zeilen mit einer Tournummer (inkl. Duplikate)
print(df_soll['TOURNR'].count())

2800

In [174]:
df_soll.duplicated().any()

np.True_

In [175]:
# Häufigkeit jeder Tournummer
print(df_soll['TOURNR'].value_counts())

TOURNR
H/42519    77
H/42518    50
H/42444    47
H/42520    40
H/42441    39
           ..
H/42446     3
H/42638     3
H/42605     3
H/42606     3
H/42675     3
Name: count, Length: 265, dtype: int64

In [176]:
# Alle Einträge für Tournummer H/42519
df_tour = df_soll[df_soll['TOURNR'] == 'H/42519']

print(df_tour)

       TOURNR   LKW_KENNZ        FAHRERNAME     TOUR           ANKUNFT  \
1318  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 06:00
1319  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 06:00
1320  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 06:25
1321  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 06:45
1322  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 07:05
...       ...         ...               ...      ...               ...
1390  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 19:30
1391  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 19:45
1392  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 19:50
1393  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 20:05
1394  H/42519  Mafi Greif  Stoffer, Andreas  H/42519  17.03.2026 20:10

               ABFAHRT     GEOX      GEOY
1318  17.03.2026 06:00  9.98632  53.52348
1319  17.03.2026 06:05  0.00000   0.00000
1320  17.03.2026 06:45  9.98632  53.52348
1321  17.03.2026 07:05  0.00000   0.00000
1322  17.03.2026 07:25  9.98632  53.52348
...                ...      ...       ...
1390  17.03.2026 19:45  9.98632  53.52348
1391  17.03.2026 19:50  9.98632  53.52348
1392  17.03.2026 20:05  9.98632  53.52348
1393  17.03.2026 20:10  9.98632  53.52348
1394  17.03.2026 20:25  9.98632  53.52348

[77 rows x 8 columns]

Die LKW Kennzeichnung  Mafi Greif sollte aufjedenfall gelöscht werden.

In [177]:
df_soll = df_soll[df_soll['LKW_KENNZ'] != 'Mafi Greif']

In [178]:
# Häufigkeit jeder Tournummer
print(df_soll['TOURNR'].value_counts())

TOURNR
H/42510    20
H/42480    17
H/42513    17
H/42488    17
H/42450    17
           ..
H/42570     3
H/42638     3
H/42675     3
H/42696     3
H/42722     3
Name: count, Length: 240, dtype: int64

In [179]:
# Anzahl aller Zeilen mit einer Tournummer (inkl. Duplikate)
print(df_soll['TOURNR'].count())

1991

In [180]:
df_soll

,TOURNR,LKW_KENNZ,FAHRERNAME,TOUR,ANKUNFT,ABFAHRT,GEOX,GEOY
0,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 06:00,02.03.2026 06:00,9.98632,53.52348
1,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 06:00,02.03.2026 06:30,9.98632,53.52348
2,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 06:49,02.03.2026 07:19,9.99383,53.54751
3,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 07:41,02.03.2026 08:11,9.98632,53.52348
4,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,02.03.2026 08:31,02.03.2026 09:01,9.99383,53.54751
...,...,...,...,...,...,...,...,...
2795,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,07.04.2026 06:00,07.04.2026 06:00,9.98632,53.52348
2796,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,07.04.2026 06:57,07.04.2026 07:27,10.09782,53.53610
2797,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,07.04.2026 07:53,07.04.2026 08:23,9.98632,53.52348
2798,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,07.04.2026 09:52,07.04.2026 10:22,9.51017,53.64711
2799,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,07.04.2026 11:52,07.04.2026 11:52,9.98632,53.52348

In [181]:
df_soll['ANKUNFT'] = pd.to_datetime(df_soll['ANKUNFT'], format='%d.%m.%Y %H:%M')
df_soll['ABFAHRT'] = pd.to_datetime(df_soll['ABFAHRT'], format='%d.%m.%Y %H:%M')

# Stoppdauer berechnen
df_soll['STOPP_DAUER'] = df_soll['ABFAHRT'] - df_soll['ANKUNFT']

# Fehlerhafte Einträge: Abfahrt vor Ankunft
fehler_zeit = df_soll[df_soll['STOPP_DAUER'] < pd.Timedelta(0)]
print(f"Zeitfehler: {len(fehler_zeit)} Einträge")
print(fehler_zeit)

Zeitfehler: 0 Einträge
Empty DataFrame
Columns: [TOURNR, LKW_KENNZ, FAHRERNAME, TOUR, ANKUNFT, ABFAHRT, GEOX, GEOY, STOPP_DAUER]
Index: []

In [182]:
df_soll.nunique()

TOURNR          240
LKW_KENNZ        14
FAHRERNAME       15
TOUR            240
ANKUNFT        1516
ABFAHRT        1593
GEOX            237
GEOY            238
STOPP_DAUER      30
dtype: int64

In [183]:
df_soll["FAHRERNAME"].unique()

array(['Hesse, Sven-Erik', 'Szmajdewicz, Marcin', 'Krüger, Alexander',
       'Jorczik, Christian', 'Ledwina, Jens', 'Borrs, Thomas',
       'Calina, Florin Alexandru', 'Oelschlaeger, Marcel',
       'Giewon, Mariusz', 'Staben, Volker', 'Schulz, Frank',
       'Teme, Abdoulaye', 'Hrzuska, Krzystof', 'Sowa, Mariusz', nan,
       'Stoffer, Andreas'], dtype=object)

In [184]:
# Stopps pro Tour sortiert nach Ankunftszeit
df_sorted = df_soll.sort_values(['TOURNR', 'ANKUNFT'])

# Überblick: Wie viele Stopps hat jede Tour?
print(df_sorted.groupby('TOURNR').size().rename('Anzahl Stopps'))

TOURNR
H/42374     6
H/42375     7
H/42376    10
H/42377     6
H/42378     6
           ..
H/42742    16
H/42746     4
H/42750     8
H/42754     7
H/42758     5
Name: Anzahl Stopps, Length: 240, dtype: int64

In [185]:
df_soll['STOPP_DAUER'] = df_soll['ABFAHRT'] - df_soll['ANKUNFT']
fehler_zeit = df_soll[df_soll['STOPP_DAUER'] < pd.Timedelta(0)]
print(f"Zeitfehler: {len(fehler_zeit)} Einträge")

Zeitfehler: 0 Einträge

In [186]:
df_soll['STOPP_DAUER'].describe()

count                         1991
mean     0 days 00:25:48.789552988
std      0 days 00:33:14.678571708
min                0 days 00:00:00
25%                0 days 00:15:00
50%                0 days 00:30:00
75%                0 days 00:30:00
max                0 days 14:08:00
Name: STOPP_DAUER, dtype: object

In [187]:
dateien = [
    'Einzelmeldungsreport_HTS-Cargo_GmbH_1.xlsx',
    'Einzelmeldungsreport_HTS-Cargo_GmbH_2.xlsx',
    'Einzelmeldungsreport_HTS-Cargo_GmbH_3.xlsx',
    'Einzelmeldungsreport_HTS-Cargo_GmbH_4.xlsx',
    'Einzelmeldungsreport_HTS-Cargo_GmbH_5.xlsx',
]

ist_frames = []

for datei in dateien:
    alle_blaetter = pd.read_excel(datei, sheet_name=None, header=8)
    for blatt_name, blatt_df in alle_blaetter.items():
        if 'Formularbeschreibung' in blatt_df.columns:
            gefiltert = blatt_df[blatt_df['Formularbeschreibung'].isin(['Ankunft Kunde', 'Abfahrt Kunde'])].copy()
            gefiltert['Fahrzeug'] = blatt_name  # Fahrzeugname als Spalte speichern
            if not gefiltert.empty:
                ist_frames.append(gefiltert)

df_ist = pd.concat(ist_frames, ignore_index=True)
print(f"Ist-Daten: {len(df_ist)} Einträge")
print(df_ist.columns.tolist())

Ist-Daten: 2875 Einträge
['Fahrer PIN', 'Fahrername', 'Formularnummer', 'Formularbeschreibung', 'Meldungszeit', 'Richtung', 'Geschwindigkeit', 'KM-Stand', 'Gesamtverbrauch', 'Tankfüllstand', 'Breitengrad', 'Längengrad', 'Position', 'Meldungsquelle', 'Fahrzeug']

In [188]:
df_ist

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 05:19:13,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:00:13,0,0,316550.025,0.0,0.0,"53,66757","9,9928","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:33:59,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:34:00,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:54:21,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 11:49:13,208,0,502860.415,0.0,0.0,"53,51717","9,96982","DE - 20457 Hamburg (Hamburg-Mitte), Köhlbrandb...",SPEDION App,TS859 - Fahrzeugdetails
2871,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 11:59:39,0,0,502863.510,0.0,0.0,"53,52261","9,98925","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails
2872,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 12:11:29,0,0,502863.755,0.0,0.0,"53,5228","9,98903","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails
2873,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 12:37:22,0,0,502869.170,0.0,0.0,"53,5341","9,98237","DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 32",SPEDION App,TS859 - Fahrzeugdetails
2874,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 13:04:35,0,0,502874.385,0.0,0.0,"53,52344","9,98587","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails

In [189]:
df_ist = df_ist[~df_ist['Fahrzeug'].str.contains('Mafi', case=False, na=False)]

In [190]:
df_ist

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 05:19:13,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:00:13,0,0,316550.025,0.0,0.0,"53,66757","9,9928","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:33:59,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:34:00,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:54:21,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",SPEDION App,OD-TS 8041 - Fahrzeugdetails
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 11:49:13,208,0,502860.415,0.0,0.0,"53,51717","9,96982","DE - 20457 Hamburg (Hamburg-Mitte), Köhlbrandb...",SPEDION App,TS859 - Fahrzeugdetails
2871,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 11:59:39,0,0,502863.510,0.0,0.0,"53,52261","9,98925","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails
2872,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 12:11:29,0,0,502863.755,0.0,0.0,"53,5228","9,98903","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails
2873,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 12:37:22,0,0,502869.170,0.0,0.0,"53,5341","9,98237","DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 32",SPEDION App,TS859 - Fahrzeugdetails
2874,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 13:04:35,0,0,502874.385,0.0,0.0,"53,52344","9,98587","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails

In [191]:
# Soll-Daten: Datum aus ANKUNFT extrahieren
df_soll['DATUM'] = df_soll['ANKUNFT'].dt.date

# Ist-Daten: Meldungszeit parsen und Datum extrahieren
df_ist['Meldungszeit'] = pd.to_datetime(df_ist['Meldungszeit'], format='%d.%m.%Y %H:%M:%S', errors='coerce')
df_ist['DATUM'] = df_ist['Meldungszeit'].dt.date

In [192]:
df_ist

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug,DATUM
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 05:19:13,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:00:13,0,0,316550.025,0.0,0.0,"53,66757","9,9928","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:33:59,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:34:00,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:54:21,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 11:49:13,208,0,502860.415,0.0,0.0,"53,51717","9,96982","DE - 20457 Hamburg (Hamburg-Mitte), Köhlbrandb...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06
2871,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 11:59:39,0,0,502863.510,0.0,0.0,"53,52261","9,98925","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06
2872,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 12:11:29,0,0,502863.755,0.0,0.0,"53,5228","9,98903","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06
2873,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 12:37:22,0,0,502869.170,0.0,0.0,"53,5341","9,98237","DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 32",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06
2874,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 13:04:35,0,0,502874.385,0.0,0.0,"53,52344","9,98587","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06

In [193]:
df_soll

,TOURNR,LKW_KENNZ,FAHRERNAME,TOUR,ANKUNFT,ABFAHRT,GEOX,GEOY,STOPP_DAUER,DATUM
0,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 06:00:00,2026-03-02 06:00:00,9.98632,53.52348,0 days 00:00:00,2026-03-02
1,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 06:00:00,2026-03-02 06:30:00,9.98632,53.52348,0 days 00:30:00,2026-03-02
2,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 06:49:00,2026-03-02 07:19:00,9.99383,53.54751,0 days 00:30:00,2026-03-02
3,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 07:41:00,2026-03-02 08:11:00,9.98632,53.52348,0 days 00:30:00,2026-03-02
4,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 08:31:00,2026-03-02 09:01:00,9.99383,53.54751,0 days 00:30:00,2026-03-02
...,...,...,...,...,...,...,...,...,...,...
2795,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 06:00:00,2026-04-07 06:00:00,9.98632,53.52348,0 days 00:00:00,2026-04-07
2796,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 06:57:00,2026-04-07 07:27:00,10.09782,53.53610,0 days 00:30:00,2026-04-07
2797,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 07:53:00,2026-04-07 08:23:00,9.98632,53.52348,0 days 00:30:00,2026-04-07
2798,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 09:52:00,2026-04-07 10:22:00,9.51017,53.64711,0 days 00:30:00,2026-04-07
2799,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 11:52:00,2026-04-07 11:52:00,9.98632,53.52348,0 days 00:00:00,2026-04-07

In [194]:
df_ist.nunique()

Fahrer PIN                11
Fahrername                11
Formularnummer             2
Formularbeschreibung       2
Meldungszeit            2753
Richtung                 314
Geschwindigkeit            5
KM-Stand                1421
Gesamtverbrauch          637
Tankfüllstand            176
Breitengrad             1066
Längengrad              1294
Position                 375
Meldungsquelle             1
Fahrzeug                  12
DATUM                     24
dtype: int64

In [195]:
df_ist['Fahrzeug'].unique()

array(['OD-TS 8041 - Fahrzeugdetails', 'OD-TS 8046 - Fahrzeugdetails',
       'OD-TS 8048 - Fahrzeugdetails', 'OD-TS 8050 - Fahrzeugdetails',
       'PI-EN 444 - Fahrzeugdetails', 'PI-EN 900 - Fahrzeugdetails',
       'Plo-TS857 - Fahrzeugdetails', 'Plö-TS853 - Fahrzeugdetails',
       'Plö-TS856 - Fahrzeugdetails', 'TS859 - Fahrzeugdetails',
       'WL-PL431 - Fahrzeugdetails', 'OD-TS 8044 - Fahrzeugdetails'],
      dtype=object)

In [196]:
df_ist['Fahrername'].unique()

array(['Jorczik, Christian', 'Calina, Florin Alexandru',
       'Oelschläger, Marcel', 'Szmajdewicz, Marcin', 'Giewon, Mariusz',
       'Teme, Abdoulaeye', 'Ledwina, Jens', 'Borrs, Thomas',
       'Hesse, Sven-Erik', 'Krüger, Alexander', 'Hruszka, Krzysztof'],
      dtype=object)

In [197]:
df_ist['DATUM'].unique()

array([datetime.date(2026, 3, 24), datetime.date(2026, 3, 25),
       datetime.date(2026, 3, 26), datetime.date(2026, 3, 23),
       datetime.date(2026, 3, 27), datetime.date(2026, 3, 30),
       datetime.date(2026, 3, 31), datetime.date(2026, 4, 1),
       datetime.date(2026, 4, 2), datetime.date(2026, 3, 16),
       datetime.date(2026, 3, 17), datetime.date(2026, 3, 19),
       datetime.date(2026, 3, 18), datetime.date(2026, 3, 20),
       datetime.date(2026, 3, 10), datetime.date(2026, 3, 11),
       datetime.date(2026, 3, 12), datetime.date(2026, 3, 13),
       datetime.date(2026, 3, 9), datetime.date(2026, 3, 2),
       datetime.date(2026, 3, 4), datetime.date(2026, 3, 5),
       datetime.date(2026, 3, 3), datetime.date(2026, 3, 6)], dtype=object)

In [198]:
# Gesamtanzahl Fahrten (eindeutige Fahrername + Datum Kombinationen)
anzahl_fahrten = df_ist.groupby(['Fahrername', 'DATUM']).ngroups
print(f"Gesamtanzahl Fahrten: {anzahl_fahrten}")

Gesamtanzahl Fahrten: 213

In [199]:
df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].nunique().max()
# Wenn > 1, gibt es Tage mit mehreren Touren

np.int64(3)

In [200]:
df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].unique()

FAHRERNAME       DATUM
Borrs, Thomas    2026-03-02    [H/42379]
                 2026-03-03    [H/42396]
                 2026-03-04    [H/42408]
                 2026-03-05    [H/42423]
                 2026-03-06    [H/42435]
                                 ...
Teme, Abdoulaye  2026-03-27    [H/42602]
                 2026-03-30    [H/42652]
                 2026-03-31    [H/42663]
                 2026-04-02    [H/42673]
                 2026-04-07    [H/42758]
Name: TOURNR, Length: 229, dtype: object

In [201]:
df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].nunique()

FAHRERNAME       DATUM
Borrs, Thomas    2026-03-02    1
                 2026-03-03    1
                 2026-03-04    1
                 2026-03-05    1
                 2026-03-06    1
                              ..
Teme, Abdoulaye  2026-03-27    1
                 2026-03-30    1
                 2026-03-31    1
                 2026-04-02    1
                 2026-04-07    1
Name: TOURNR, Length: 229, dtype: int64

In [202]:
# Anzahl eindeutiger Touren pro Fahrer + Tag
touren_pro_tag = df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].nunique()

# Wie oft gibt es mehr als 1 Tour pro Tag
print((touren_pro_tag > 1).sum(), "Fahrer-Tag-Kombinationen mit mehr als 1 Tour")
print(touren_pro_tag.value_counts().sort_index())

9 Fahrer-Tag-Kombinationen mit mehr als 1 Tour
TOURNR
1    220
2      7
3      2
Name: count, dtype: int64

In [203]:
# Tage mit mehr als 1 Tour identifizieren
touren_pro_tag = df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].nunique()
mehrfach_mask = touren_pro_tag[touren_pro_tag > 1].reset_index()
mehrfach_mask.columns = ['FAHRERNAME', 'DATUM', 'ANZAHL_TOUREN']

# Tournummern dazu joinen
tournummern = df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'] \
    .apply(lambda x: ', '.join(x.unique())).reset_index()
tournummern.columns = ['FAHRERNAME', 'DATUM', 'TOURNUMMERN']

# Zusammenführen
ergebnis = mehrfach_mask.merge(tournummern, on=['FAHRERNAME', 'DATUM']) \
    .sort_values(['ANZAHL_TOUREN', 'DATUM'], ascending=[False, True])

print(ergebnis.to_string(index=False))

              FAHRERNAME      DATUM  ANZAHL_TOUREN               TOURNUMMERN
     Szmajdewicz, Marcin 2026-03-19              3 H/42547, H/42549, H/42556
     Szmajdewicz, Marcin 2026-03-20              3 H/42561, H/42568, H/42587
       Krüger, Alexander 2026-03-03              2          H/42393, H/42415
         Teme, Abdoulaye 2026-03-11              2          H/42468, H/42505
     Szmajdewicz, Marcin 2026-03-18              2          H/42536, H/42544
Calina, Florin Alexandru 2026-03-23              2          H/42571, H/42578
Calina, Florin Alexandru 2026-03-26              2          H/42601, H/42628
       Krüger, Alexander 2026-03-31              2          H/42646, H/42657
    Oelschlaeger, Marcel 2026-04-01              2          H/42681, H/42695

In [204]:
# Tage mit mehr als 1 Tour identifizieren
touren_pro_tag = df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].nunique()
mehrfach_mask = touren_pro_tag[touren_pro_tag > 1].reset_index()
mehrfach_mask.columns = ['FAHRERNAME', 'DATUM', 'ANZAHL_TOUREN']

# Tournummern und Kennzeichen dazu joinen
details = df_soll.groupby(['FAHRERNAME', 'DATUM']).agg(
    TOURNUMMERN=('TOURNR', lambda x: ', '.join(x.unique())),
    KENNZEICHEN=('LKW_KENNZ', lambda x: ', '.join(x.unique()))
).reset_index()

# Zusammenführen
ergebnis = mehrfach_mask.merge(details, on=['FAHRERNAME', 'DATUM']) \
    .sort_values(['ANZAHL_TOUREN', 'DATUM'], ascending=[False, True])

print(ergebnis.to_string(index=False))

              FAHRERNAME      DATUM  ANZAHL_TOUREN               TOURNUMMERN                    KENNZEICHEN
     Szmajdewicz, Marcin 2026-03-19              3 H/42547, H/42549, H/42556 PI-EN 900, OD-TS8050, WL-PL431
     Szmajdewicz, Marcin 2026-03-20              3 H/42561, H/42568, H/42587 OD-TS8050, WL-PL431, PI-EN 900
       Krüger, Alexander 2026-03-03              2          H/42393, H/42415           Plo-TS859, PI-EN 900
         Teme, Abdoulaye 2026-03-11              2          H/42468, H/42505           PI-EN 900, OD-TS8050
     Szmajdewicz, Marcin 2026-03-18              2          H/42536, H/42544            OD-TS8050, WL-PL431
Calina, Florin Alexandru 2026-03-23              2          H/42571, H/42578           PI-EN 900, OD-TS8046
Calina, Florin Alexandru 2026-03-26              2          H/42601, H/42628            OD-TS8046, WL-PL431
       Krüger, Alexander 2026-03-31              2          H/42646, H/42657                      Plo-TS859
    Oelschlaeger, Marcel 2026-04-01              2          H/42681, H/42695            OD-TS8048, WL-PL431

In [205]:
df_soll

,TOURNR,LKW_KENNZ,FAHRERNAME,TOUR,ANKUNFT,ABFAHRT,GEOX,GEOY,STOPP_DAUER,DATUM
0,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 06:00:00,2026-03-02 06:00:00,9.98632,53.52348,0 days 00:00:00,2026-03-02
1,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 06:00:00,2026-03-02 06:30:00,9.98632,53.52348,0 days 00:30:00,2026-03-02
2,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 06:49:00,2026-03-02 07:19:00,9.99383,53.54751,0 days 00:30:00,2026-03-02
3,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 07:41:00,2026-03-02 08:11:00,9.98632,53.52348,0 days 00:30:00,2026-03-02
4,H/42374,Plo-TS856,"Hesse, Sven-Erik",H/42374,2026-03-02 08:31:00,2026-03-02 09:01:00,9.99383,53.54751,0 days 00:30:00,2026-03-02
...,...,...,...,...,...,...,...,...,...,...
2795,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 06:00:00,2026-04-07 06:00:00,9.98632,53.52348,0 days 00:00:00,2026-04-07
2796,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 06:57:00,2026-04-07 07:27:00,10.09782,53.53610,0 days 00:30:00,2026-04-07
2797,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 07:53:00,2026-04-07 08:23:00,9.98632,53.52348,0 days 00:30:00,2026-04-07
2798,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 09:52:00,2026-04-07 10:22:00,9.51017,53.64711,0 days 00:30:00,2026-04-07
2799,H/42758,PI-EN 444,"Teme, Abdoulaye",H/42758,2026-04-07 11:52:00,2026-04-07 11:52:00,9.98632,53.52348,0 days 00:00:00,2026-04-07

In [206]:
df_ist["Fahrzeug"].unique()

array(['OD-TS 8041 - Fahrzeugdetails', 'OD-TS 8046 - Fahrzeugdetails',
       'OD-TS 8048 - Fahrzeugdetails', 'OD-TS 8050 - Fahrzeugdetails',
       'PI-EN 444 - Fahrzeugdetails', 'PI-EN 900 - Fahrzeugdetails',
       'Plo-TS857 - Fahrzeugdetails', 'Plö-TS853 - Fahrzeugdetails',
       'Plö-TS856 - Fahrzeugdetails', 'TS859 - Fahrzeugdetails',
       'WL-PL431 - Fahrzeugdetails', 'OD-TS 8044 - Fahrzeugdetails'],
      dtype=object)

In [207]:
df_soll["LKW_KENNZ"].unique()

array(['Plo-TS856', 'OD-TS8050', 'Plo-TS859', 'OD-TS8041', 'OD-TS8044',
       'Plö-TS853', 'OD-TS8046', 'OD-TS8048', 'PI-EN 444', 'RW435',
       'PI-EN 900', 'WL-PL431', 'Leihwagen', 'Plö-TS857'], dtype=object)

In [208]:
# Schritt 1: " - Fahrzeugdetails" entfernen
df_ist['KENNZ_CLEAN'] = df_ist['Fahrzeug'].str.replace(' - Fahrzeugdetails', '', regex=False)

# Schritt 2: OD-TS Leerzeichen entfernen
df_ist['KENNZ_CLEAN'] = df_ist['KENNZ_CLEAN'].str.replace('OD-TS ', 'OD-TS', regex=False)

# Schritt 3: Manuelle Korrekturen
korrekturen = {
    'Plo-TS857': 'Plö-TS857',
    'Plö-TS856': 'Plo-TS856',
    'TS859':     'Plo-TS859'
}
df_ist['KENNZ_CLEAN'] = df_ist['KENNZ_CLEAN'].replace(korrekturen)

In [209]:
df_soll["LKW_KENNZ"].unique()

array(['Plo-TS856', 'OD-TS8050', 'Plo-TS859', 'OD-TS8041', 'OD-TS8044',
       'Plö-TS853', 'OD-TS8046', 'OD-TS8048', 'PI-EN 444', 'RW435',
       'PI-EN 900', 'WL-PL431', 'Leihwagen', 'Plö-TS857'], dtype=object)

In [210]:
df_ist['KENNZ_CLEAN'].unique()

array(['OD-TS8041', 'OD-TS8046', 'OD-TS8048', 'OD-TS8050', 'PI-EN 444',
       'PI-EN 900', 'Plö-TS857', 'Plö-TS853', 'Plo-TS856', 'Plo-TS859',
       'WL-PL431', 'OD-TS8044'], dtype=object)

In [211]:
df_soll["FAHRERNAME"].unique()

array(['Hesse, Sven-Erik', 'Szmajdewicz, Marcin', 'Krüger, Alexander',
       'Jorczik, Christian', 'Ledwina, Jens', 'Borrs, Thomas',
       'Calina, Florin Alexandru', 'Oelschlaeger, Marcel',
       'Giewon, Mariusz', 'Staben, Volker', 'Schulz, Frank',
       'Teme, Abdoulaye', 'Hrzuska, Krzystof', 'Sowa, Mariusz', nan,
       'Stoffer, Andreas'], dtype=object)

In [212]:
df_ist['Fahrername'].unique()

array(['Jorczik, Christian', 'Calina, Florin Alexandru',
       'Oelschläger, Marcel', 'Szmajdewicz, Marcin', 'Giewon, Mariusz',
       'Teme, Abdoulaeye', 'Ledwina, Jens', 'Borrs, Thomas',
       'Hesse, Sven-Erik', 'Krüger, Alexander', 'Hruszka, Krzysztof'],
      dtype=object)

In [213]:
namen_korrekturen = {
    'Oelschläger, Marcel': 'Oelschlaeger, Marcel',
    'Teme, Abdoulaeye':    'Teme, Abdoulaye',
    'Hruszka, Krzysztof':  'Hrzuska, Krzystof'  # df_soll als Referenz
}

df_ist['Fahrername'] = df_ist['Fahrername'].replace(namen_korrekturen)

# Kontrolle
print(set(df_ist['Fahrername'].unique()) - set(df_soll['FAHRERNAME'].unique()))
# sollte set() ausgeben

set()

In [214]:
print(set(df_ist['KENNZ_CLEAN'].unique()) - set(df_soll['LKW_KENNZ'].unique()))

set()

In [215]:
df_ist

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug,DATUM,KENNZ_CLEAN
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 05:19:13,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:00:13,0,0,316550.025,0.0,0.0,"53,66757","9,9928","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:33:59,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:34:00,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:54:21,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 11:49:13,208,0,502860.415,0.0,0.0,"53,51717","9,96982","DE - 20457 Hamburg (Hamburg-Mitte), Köhlbrandb...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859
2871,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 11:59:39,0,0,502863.510,0.0,0.0,"53,52261","9,98925","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859
2872,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 12:11:29,0,0,502863.755,0.0,0.0,"53,5228","9,98903","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859
2873,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 12:37:22,0,0,502869.170,0.0,0.0,"53,5341","9,98237","DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 32",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859
2874,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 13:04:35,0,0,502874.385,0.0,0.0,"53,52344","9,98587","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859

In [216]:
touren_detail = df_soll.groupby(['FAHRERNAME', 'LKW_KENNZ', 'DATUM'])['TOURNR'].nunique()

# Nur die mit mehr als 1 Tour
mehrfach = touren_detail[touren_detail > 1].reset_index()
mehrfach.columns = ['FAHRERNAME', 'LKW_KENNZ', 'DATUM', 'ANZAHL_TOUREN']

In [217]:
# Tournummern dazu
tournr = df_soll.groupby(['FAHRERNAME', 'LKW_KENNZ', 'DATUM'])['TOURNR'] \
    .apply(lambda x: ', '.join(x.unique())).reset_index()
tournr.columns = ['FAHRERNAME', 'LKW_KENNZ', 'DATUM', 'TOURNUMMERN']

ergebnis = mehrfach.merge(tournr, on=['FAHRERNAME', 'LKW_KENNZ', 'DATUM']) \
    .sort_values(['ANZAHL_TOUREN', 'DATUM'], ascending=[False, True])

print(f"Anzahl betroffener Fahrer-Fahrzeug-Tag Kombinationen: {len(ergebnis)}")
print(ergebnis.to_string(index=False))

Anzahl betroffener Fahrer-Fahrzeug-Tag Kombinationen: 1
       FAHRERNAME LKW_KENNZ      DATUM  ANZAHL_TOUREN      TOURNUMMERN
Krüger, Alexander Plo-TS859 2026-03-31              2 H/42646, H/42657

In [218]:
# Schritt 1: Eindeutiges Mapping erstellen (eine Tournr pro Fahrer+Kennz+Datum)
tour_mapping = df_soll.groupby(['FAHRERNAME', 'LKW_KENNZ', 'DATUM'])['TOURNR'] \
    .apply(lambda x: x.iloc[0]).reset_index()  # erstmal erste Tour nehmen
tour_mapping.columns = ['Fahrername', 'KENNZ_CLEAN', 'DATUM', 'TOURNR']

# Schritt 2: Merge auf df_ist
df_ist_merged = df_ist.merge(tour_mapping, on=['Fahrername', 'KENNZ_CLEAN', 'DATUM'], how='left')

# Schritt 3: Kontrolle
print(df_ist_merged['TOURNR'].isna().sum(), "Zeilen ohne Tournummer")
print(df_ist_merged['TOURNR'].notna().sum(), "Zeilen mit Tournummer")

261 Zeilen ohne Tournummer
2614 Zeilen mit Tournummer

In [219]:
df_ist_merged[df_ist_merged.TOURNR.isna()]

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR
253,8314.0,"Teme, Abdoulaye",1650,Ankunft Kunde,2026-03-23 11:45:25,0,0,143826.335,45835.272,44.0,"53,51678","9,96972","DE - 20457 Hamburg (Hamburg-Mitte), Neuhöfer D...",SPEDION App,PI-EN 900 - Fahrzeugdetails,2026-03-23,PI-EN 900,NaN
254,8314.0,"Teme, Abdoulaye",1651,Abfahrt Kunde,2026-03-23 11:45:26,0,0,143826.335,45835.272,44.0,"53,51678","9,96972","DE - 20457 Hamburg (Hamburg-Mitte), Neuhöfer D...",SPEDION App,PI-EN 900 - Fahrzeugdetails,2026-03-23,PI-EN 900,NaN
255,8314.0,"Teme, Abdoulaye",1650,Ankunft Kunde,2026-03-23 14:09:15,0,0,143909.580,45861.824,24.0,"53,63088","9,50845","DE - 21683 Stade, Stader Elbstraße",SPEDION App,PI-EN 900 - Fahrzeugdetails,2026-03-23,PI-EN 900,NaN
256,8314.0,"Teme, Abdoulaye",1651,Abfahrt Kunde,2026-03-23 14:09:16,0,0,143909.580,45861.824,24.0,"53,63088","9,50845","DE - 21683 Stade, Stader Elbstraße",SPEDION App,PI-EN 900 - Fahrzeugdetails,2026-03-23,PI-EN 900,NaN
480,8311.0,"Szmajdewicz, Marcin",1650,Ankunft Kunde,2026-03-24 07:48:59,329,0,807302.125,0.000,0.0,"53,52322","9,98857","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,WL-PL431 - Fahrzeugdetails,2026-03-24,WL-PL431,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2702,8197.0,"Hrzuska, Krzystof",1651,Abfahrt Kunde,2026-03-06 13:50:54,0,0,179191.380,50937.052,32.0,"53,5226","9,98912","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,PI-EN 444 - Fahrzeugdetails,2026-03-06,PI-EN 444,NaN
2703,8197.0,"Hrzuska, Krzystof",1650,Ankunft Kunde,2026-03-06 13:50:57,0,0,179191.380,50937.052,32.0,"53,5226","9,98912","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,PI-EN 444 - Fahrzeugdetails,2026-03-06,PI-EN 444,NaN
2704,8197.0,"Hrzuska, Krzystof",1651,Abfahrt Kunde,2026-03-06 13:50:59,0,0,179191.380,50937.052,32.0,"53,5226","9,98912","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,PI-EN 444 - Fahrzeugdetails,2026-03-06,PI-EN 444,NaN
2705,8317.0,"Hesse, Sven-Erik",1650,Ankunft Kunde,2026-03-03 06:55:23,0,0,143469.000,45685.036,4.8,"53,53563","9,97776","DE - 20457 Hamburg (Hamburg-Mitte), Stillhorne...",SPEDION App,PI-EN 900 - Fahrzeugdetails,2026-03-03,PI-EN 900,NaN
2706,8317.0,"Hesse, Sven-Erik",1651,Abfahrt Kunde,2026-03-03 09:19:42,0,0,143469.515,45685.880,6.0,"53,53433","9,9806","DE - 20457 Hamburg (Hamburg-Mitte), Werftstraße 5",SPEDION App,PI-EN 900 - Fahrzeugdetails,2026-03-03,PI-EN 900,NaN

In [220]:
# Welche Fahrer-Kennz-Datum Kombinationen haben kein Match?
keine_tour = df_ist_merged[df_ist_merged['TOURNR'].isna()]

print("=== Fehlende Matches nach Fahrer ===")
print(keine_tour.groupby('Fahrername').size().sort_values(ascending=False))

print("\n=== Fehlende Matches nach KENNZ_CLEAN ===")
print(keine_tour.groupby('KENNZ_CLEAN').size().sort_values(ascending=False))

print("\n=== Fehlende Matches nach DATUM ===")
print(keine_tour.groupby('DATUM').size().sort_values(ascending=False))

# Eindeutige Kombinationen die kein Match haben
print("\n=== Fahrer+Kennz+Datum ohne Match ===")
print(keine_tour.groupby(['Fahrername', 'KENNZ_CLEAN', 'DATUM']).size().reset_index().to_string(index=False))

=== Fehlende Matches nach Fahrer ===
Fahrername
Hrzuska, Krzystof           224
Teme, Abdoulaye              22
Szmajdewicz, Marcin           8
Calina, Florin Alexandru      4
Hesse, Sven-Erik              2
Ledwina, Jens                 1
dtype: int64

=== Fehlende Matches nach KENNZ_CLEAN ===
KENNZ_CLEAN
PI-EN 444    138
OD-TS8050     70
WL-PL431      35
PI-EN 900     17
OD-TS8044      1
dtype: int64

=== Fehlende Matches nach DATUM ===
DATUM
2026-03-19    37
2026-03-05    33
2026-03-06    29
2026-03-02    28
2026-03-03    26
2026-03-04    24
2026-03-20    21
2026-03-18    20
2026-03-13    20
2026-03-24     8
2026-03-09     4
2026-03-23     4
2026-04-01     4
2026-03-26     3
dtype: int64

=== Fahrer+Kennz+Datum ohne Match ===
              Fahrername KENNZ_CLEAN      DATUM  0
Calina, Florin Alexandru   OD-TS8050 2026-03-09  4
        Hesse, Sven-Erik   PI-EN 900 2026-03-03  2
       Hrzuska, Krzystof   OD-TS8050 2026-03-18 20
       Hrzuska, Krzystof   OD-TS8050 2026-03-19 26
       Hrzuska, Krzystof   OD-TS8050 2026-03-20 20
       Hrzuska, Krzystof   PI-EN 444 2026-03-02 28
       Hrzuska, Krzystof   PI-EN 444 2026-03-03 24
       Hrzuska, Krzystof   PI-EN 444 2026-03-04 24
       Hrzuska, Krzystof   PI-EN 444 2026-03-05 33
       Hrzuska, Krzystof   PI-EN 444 2026-03-06 29
       Hrzuska, Krzystof    WL-PL431 2026-03-13 20
           Ledwina, Jens   OD-TS8044 2026-03-20  1
     Szmajdewicz, Marcin    WL-PL431 2026-03-24  8
         Teme, Abdoulaye   PI-EN 900 2026-03-19 11
         Teme, Abdoulaye   PI-EN 900 2026-03-23  4
         Teme, Abdoulaye    WL-PL431 2026-03-26  3
         Teme, Abdoulaye    WL-PL431 2026-04-01  4

In [221]:
# 1. Welche Kennzeichen fährt Hrzuska in df_ist?
print("=== Hrzuska in df_ist ===")
print(df_ist[df_ist['Fahrername'] == 'Hrzuska, Krzystof']
      .groupby(['KENNZ_CLEAN', 'DATUM']).size().reset_index().to_string(index=False))

# 2. Welche Kennzeichen hat Hrzuska in df_soll?
print("\n=== Hrzuska in df_soll ===")
print(df_soll[df_soll['FAHRERNAME'] == 'Hrzuska, Krzystof']
      .groupby(['LKW_KENNZ', 'DATUM']).size().reset_index().to_string(index=False))

# 3. Für Teme - welche Kennzeichen fehlen?
print("\n=== Teme in df_ist (keine Tour) ===")
keine_tour = df_ist_merged[df_ist_merged['TOURNR'].isna()]
print(keine_tour[keine_tour['Fahrername'] == 'Teme, Abdoulaye']
      .groupby(['KENNZ_CLEAN', 'DATUM']).size().reset_index().to_string(index=False))

print("\n=== Teme in df_soll ===")
print(df_soll[df_soll['FAHRERNAME'] == 'Teme, Abdoulaye']
      .groupby(['LKW_KENNZ', 'DATUM']).size().reset_index().to_string(index=False))

=== Hrzuska in df_ist ===
KENNZ_CLEAN      DATUM  0
  OD-TS8050 2026-03-17 25
  OD-TS8050 2026-03-18 20
  OD-TS8050 2026-03-19 26
  OD-TS8050 2026-03-20 20
  PI-EN 444 2026-03-02 28
  PI-EN 444 2026-03-03 24
  PI-EN 444 2026-03-04 24
  PI-EN 444 2026-03-05 33
  PI-EN 444 2026-03-06 29
  PI-EN 900 2026-03-16 22
   WL-PL431 2026-03-09 36
   WL-PL431 2026-03-10 20
   WL-PL431 2026-03-11 34
   WL-PL431 2026-03-12 16
   WL-PL431 2026-03-13 20

=== Hrzuska in df_soll ===
LKW_KENNZ      DATUM  0
OD-TS8050 2026-03-17 15
PI-EN 900 2026-03-16 13
 WL-PL431 2026-03-09 17
 WL-PL431 2026-03-10 13
 WL-PL431 2026-03-11 13
 WL-PL431 2026-03-12 12

=== Teme in df_ist (keine Tour) ===
KENNZ_CLEAN      DATUM  0
  PI-EN 900 2026-03-19 11
  PI-EN 900 2026-03-23  4
   WL-PL431 2026-03-26  3
   WL-PL431 2026-04-01  4

=== Teme in df_soll ===
LKW_KENNZ      DATUM  0
OD-TS8050 2026-03-11  3
OD-TS8050 2026-03-12  4
OD-TS8050 2026-03-13  6
PI-EN 444 2026-04-07  5
PI-EN 900 2026-03-09 10
PI-EN 900 2026-03-10  7
PI-EN 900 2026-03-11  8
PI-EN 900 2026-03-17  9
PI-EN 900 2026-03-18  5
PI-EN 900 2026-04-02  7
 WL-PL431 2026-03-24  4
 WL-PL431 2026-03-25  3
 WL-PL431 2026-03-27  4
 WL-PL431 2026-03-30  5
 WL-PL431 2026-03-31  4

In [222]:
# Überblick: Wie viele Zeilen bleiben nach dem Merge ohne Tour?
print(f"Gesamt ohne Tournummer: {df_ist_merged['TOURNR'].isna().sum()}")

# Aufschlüsselung: Echte Datenlücken (kein Soll vorhanden) vs. mögliche Zuordnungsfehler
keine_tour = df_ist_merged[df_ist_merged['TOURNR'].isna()]

# Gibt es für den Fahrer+Datum irgendeine Tour in df_soll (unabhängig vom Kennzeichen)?
soll_fd = df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'].first().reset_index()
soll_fd.columns = ['Fahrername', 'DATUM', 'TOURNR_fallback']

keine_tour_check = keine_tour[['Fahrername', 'DATUM']].drop_duplicates() \
    .merge(soll_fd, on=['Fahrername', 'DATUM'], how='left')

print("\nMit Fallback (nur Fahrer+Datum, ohne Kennzeichen):")
print(keine_tour_check['TOURNR_fallback'].isna().value_counts())
# False = es gibt eine Tour wenn man Kennzeichen ignoriert
# True  = echter Datenfehler, kein Soll vorhanden

Gesamt ohne Tournummer: 261

Mit Fallback (nur Fahrer+Datum, ohne Kennzeichen):
TOURNR_fallback
True     14
False     3
Name: count, dtype: int64

In [223]:
# Fallback-Mapping nur Fahrer+Datum
soll_fd = df_soll.groupby(['FAHRERNAME', 'DATUM'])['TOURNR'] \
    .first().reset_index()
soll_fd.columns = ['Fahrername', 'DATUM', 'TOURNR_fallback']

df_ist_merged = df_ist_merged.merge(soll_fd, on=['Fahrername', 'DATUM'], how='left')

# Fallback nur dort eintragen wo TOURNR noch NaN ist
df_ist_merged['TOURNR'] = df_ist_merged['TOURNR'].fillna(df_ist_merged['TOURNR_fallback'])
df_ist_merged = df_ist_merged.drop(columns=['TOURNR_fallback'])

# Kontrolle
print(df_ist_merged['TOURNR'].isna().sum(), "Zeilen ohne Tournummer (echte Lücken)")
print(df_ist_merged['TOURNR'].notna().sum(), "Zeilen mit Tournummer")

254 Zeilen ohne Tournummer (echte Lücken)
2621 Zeilen mit Tournummer

In [224]:
# Welche Fahrer+Datum haben gar keine Soll-Daten?
echte_luecken = df_ist_merged[df_ist_merged['TOURNR'].isna()] \
    .groupby(['Fahrername', 'KENNZ_CLEAN', 'DATUM']).size().reset_index()
echte_luecken.columns = ['Fahrername', 'KENNZ_CLEAN', 'DATUM', 'Anzahl_Meldungen']
print(echte_luecken.to_string(index=False))

         Fahrername KENNZ_CLEAN      DATUM  Anzahl_Meldungen
  Hrzuska, Krzystof   OD-TS8050 2026-03-18                20
  Hrzuska, Krzystof   OD-TS8050 2026-03-19                26
  Hrzuska, Krzystof   OD-TS8050 2026-03-20                20
  Hrzuska, Krzystof   PI-EN 444 2026-03-02                28
  Hrzuska, Krzystof   PI-EN 444 2026-03-03                24
  Hrzuska, Krzystof   PI-EN 444 2026-03-04                24
  Hrzuska, Krzystof   PI-EN 444 2026-03-05                33
  Hrzuska, Krzystof   PI-EN 444 2026-03-06                29
  Hrzuska, Krzystof    WL-PL431 2026-03-13                20
Szmajdewicz, Marcin    WL-PL431 2026-03-24                 8
    Teme, Abdoulaye   PI-EN 900 2026-03-19                11
    Teme, Abdoulaye   PI-EN 900 2026-03-23                 4
    Teme, Abdoulaye    WL-PL431 2026-03-26                 3
    Teme, Abdoulaye    WL-PL431 2026-04-01                 4

In [225]:
# Welche Tournummern würde Hrzuska per Fallback bekommen?
print(df_soll[df_soll['FAHRERNAME'] == 'Hrzuska, Krzystof']
      [['TOURNR', 'LKW_KENNZ', 'DATUM']].drop_duplicates().to_string(index=False))

 TOURNR LKW_KENNZ      DATUM
H/42480  WL-PL431 2026-03-09
H/42481  WL-PL431 2026-03-10
H/42484  WL-PL431 2026-03-11
H/42491  WL-PL431 2026-03-12
H/42507 PI-EN 900 2026-03-16
H/42525 OD-TS8050 2026-03-17

In [226]:
df_ist_merged

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 05:19:13,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:00:13,0,0,316550.025,0.0,0.0,"53,66757","9,9928","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:33:59,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:34:00,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:54:21,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 11:49:13,208,0,502860.415,0.0,0.0,"53,51717","9,96982","DE - 20457 Hamburg (Hamburg-Mitte), Köhlbrandb...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2871,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 11:59:39,0,0,502863.510,0.0,0.0,"53,52261","9,98925","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2872,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 12:11:29,0,0,502863.755,0.0,0.0,"53,5228","9,98903","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2873,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 12:37:22,0,0,502869.170,0.0,0.0,"53,5341","9,98237","DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 32",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2874,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 13:04:35,0,0,502874.385,0.0,0.0,"53,52344","9,98587","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432

In [227]:
# Finale Statistik
gesamt = len(df_ist_merged)
mit_tour = df_ist_merged['TOURNR'].notna().sum()
ohne_tour = df_ist_merged['TOURNR'].isna().sum()

print(f"Gesamt Meldungen:       {gesamt}")
print(f"Mit Tournummer:         {mit_tour} ({mit_tour/gesamt*100:.1f}%)")
print(f"Ohne Tournummer (NaN):  {ohne_tour} ({ohne_tour/gesamt*100:.1f}%)")

# Lücken als separaten DataFrame speichern
df_luecken = df_ist_merged[df_ist_merged['TOURNR'].isna()] \
    .groupby(['Fahrername', 'KENNZ_CLEAN', 'DATUM']).size().reset_index()
df_luecken.columns = ['Fahrername', 'Kennzeichen', 'Datum', 'Anzahl_Meldungen']
df_luecken['Grund'] = 'Kein Soll-Eintrag vorhanden'
print(df_luecken)

Gesamt Meldungen:       2875
Mit Tournummer:         2621 (91.2%)
Ohne Tournummer (NaN):  254 (8.8%)
             Fahrername Kennzeichen       Datum  Anzahl_Meldungen  \
0     Hrzuska, Krzystof   OD-TS8050  2026-03-18                20
1     Hrzuska, Krzystof   OD-TS8050  2026-03-19                26
2     Hrzuska, Krzystof   OD-TS8050  2026-03-20                20
3     Hrzuska, Krzystof   PI-EN 444  2026-03-02                28
4     Hrzuska, Krzystof   PI-EN 444  2026-03-03                24
5     Hrzuska, Krzystof   PI-EN 444  2026-03-04                24
6     Hrzuska, Krzystof   PI-EN 444  2026-03-05                33
7     Hrzuska, Krzystof   PI-EN 444  2026-03-06                29
8     Hrzuska, Krzystof    WL-PL431  2026-03-13                20
9   Szmajdewicz, Marcin    WL-PL431  2026-03-24                 8
10      Teme, Abdoulaye   PI-EN 900  2026-03-19                11
11      Teme, Abdoulaye   PI-EN 900  2026-03-23                 4
12      Teme, Abdoulaye    WL-PL431  2026-03-26                 3
13      Teme, Abdoulaye    WL-PL431  2026-04-01                 4

                          Grund
0   Kein Soll-Eintrag vorhanden
1   Kein Soll-Eintrag vorhanden
2   Kein Soll-Eintrag vorhanden
3   Kein Soll-Eintrag vorhanden
4   Kein Soll-Eintrag vorhanden
5   Kein Soll-Eintrag vorhanden
6   Kein Soll-Eintrag vorhanden
7   Kein Soll-Eintrag vorhanden
8   Kein Soll-Eintrag vorhanden
9   Kein Soll-Eintrag vorhanden
10  Kein Soll-Eintrag vorhanden
11  Kein Soll-Eintrag vorhanden
12  Kein Soll-Eintrag vorhanden
13  Kein Soll-Eintrag vorhanden

In [231]:
df_ist_merged["TOURNR"].nunique()

201

In [232]:
df_soll["TOURNR"].nunique()

240

In [233]:
# Welche Touren sind in df_soll aber nicht in df_ist?
touren_soll = set(df_soll['TOURNR'].unique())
touren_ist = set(df_ist_merged['TOURNR'].dropna().unique())

fehlende_touren = touren_soll - touren_ist

# Details zu den fehlenden Touren
df_fehlend = df_soll[df_soll['TOURNR'].isin(fehlende_touren)] \
    [['TOURNR', 'FAHRERNAME', 'LKW_KENNZ', 'DATUM']].drop_duplicates() \
    .sort_values('DATUM')

print(f"Fehlende Touren: {len(fehlende_touren)}")
print(df_fehlend.to_string(index=False))

Fehlende Touren: 39
 TOURNR               FAHRERNAME LKW_KENNZ      DATUM
H/42383          Giewon, Mariusz PI-EN 444 2026-03-02
H/42416            Schulz, Frank PI-EN 900 2026-03-02
H/42400          Giewon, Mariusz PI-EN 444 2026-03-03
H/42415        Krüger, Alexander PI-EN 900 2026-03-03
H/42412          Giewon, Mariusz PI-EN 444 2026-03-04
H/42413           Staben, Volker     RW435 2026-03-04
H/42427          Giewon, Mariusz PI-EN 444 2026-03-05
H/42429            Schulz, Frank PI-EN 900 2026-03-06
H/42439          Giewon, Mariusz PI-EN 444 2026-03-06
H/42449       Jorczik, Christian OD-TS8041 2026-03-09
H/42447            Schulz, Frank OD-TS8050 2026-03-09
H/42467           Staben, Volker     RW435 2026-03-10
H/42493           Staben, Volker     RW435 2026-03-12
H/42503            Sowa, Mariusz  WL-PL431 2026-03-13
H/42533           Staben, Volker     RW435 2026-03-17
H/42536      Szmajdewicz, Marcin OD-TS8050 2026-03-18
H/42547      Szmajdewicz, Marcin PI-EN 900 2026-03-19
H/42549      Szmajdewicz, Marcin OD-TS8050 2026-03-19
H/42558           Staben, Volker     RW435 2026-03-19
H/42570                      NaN Leihwagen 2026-03-19
H/42561      Szmajdewicz, Marcin OD-TS8050 2026-03-20
H/42564       Jorczik, Christian OD-TS8041 2026-03-20
H/42571 Calina, Florin Alexandru PI-EN 900 2026-03-23
H/42590          Teme, Abdoulaye  WL-PL431 2026-03-24
H/42633           Staben, Volker     RW435 2026-03-25
H/42638          Teme, Abdoulaye  WL-PL431 2026-03-25
H/42657        Krüger, Alexander Plo-TS859 2026-03-31
H/42695     Oelschlaeger, Marcel  WL-PL431 2026-04-01
H/42701           Staben, Volker     RW435 2026-04-02
H/42754            Sowa, Mariusz  WL-PL431 2026-04-07
H/42750         Stoffer, Andreas OD-TS8048 2026-04-07
H/42746            Schulz, Frank OD-TS8050 2026-04-07
H/42742            Ledwina, Jens Plö-TS857 2026-04-07
H/42718     Oelschlaeger, Marcel PI-EN 900 2026-04-07
H/42734       Jorczik, Christian OD-TS8041 2026-04-07
H/42730        Krüger, Alexander Plo-TS859 2026-04-07
H/42722         Hesse, Sven-Erik Plo-TS856 2026-04-07
H/42738            Borrs, Thomas Plö-TS853 2026-04-07
H/42758          Teme, Abdoulaye PI-EN 444 2026-04-07

Sowa, Mariusz & Stoffer, Andreas, Frank Schulz und Staben Volker tauchen in df_ist nie auf
04.07. – massiver Ausfall - war in einzelmeldungsreport tatsächlich gar nicht inkludiert -> gar nicht in ist daten
Staben, Volker fährt immer (RW435)  Kennzeichen taucht in df_ist nie auf

-> ich würde nur mit den Zugeordneten touren weiter arbeiten

In [236]:
df_ist["KENNZ_CLEAN"].unique()

array(['OD-TS8041', 'OD-TS8046', 'OD-TS8048', 'OD-TS8050', 'PI-EN 444',
       'PI-EN 900', 'Plö-TS857', 'Plö-TS853', 'Plo-TS856', 'Plo-TS859',
       'WL-PL431', 'OD-TS8044'], dtype=object)

In [237]:
# Bestätigung: Wer ist gar nicht in df_ist?
print("In df_soll aber nie in df_ist:")
print(set(df_soll['FAHRERNAME'].dropna()) - set(df_ist['Fahrername'].unique()))

# Wie viele fehlende Touren pro Fahrer?
print("\nFehlende Touren pro Fahrer:")
print(df_fehlend.groupby('FAHRERNAME').size().sort_values(ascending=False))

# Wie viele fehlende Touren pro Datum?
print("\nFehlende Touren pro Datum:")
print(df_fehlend.groupby('DATUM').size().sort_values(ascending=False))

In df_soll aber nie in df_ist:
{'Sowa, Mariusz', 'Staben, Volker', 'Stoffer, Andreas', 'Schulz, Frank'}

Fehlende Touren pro Fahrer:
FAHRERNAME
Staben, Volker              7
Giewon, Mariusz             5
Schulz, Frank               4
Szmajdewicz, Marcin         4
Krüger, Alexander           3
Jorczik, Christian          3
Teme, Abdoulaye             3
Oelschlaeger, Marcel        2
Sowa, Mariusz               2
Borrs, Thomas               1
Hesse, Sven-Erik            1
Calina, Florin Alexandru    1
Ledwina, Jens               1
Stoffer, Andreas            1
dtype: int64

Fehlende Touren pro Datum:
DATUM
2026-04-07    10
2026-03-19     4
2026-03-02     2
2026-03-03     2
2026-03-20     2
2026-03-04     2
2026-03-09     2
2026-03-06     2
2026-03-25     2
2026-03-05     1
2026-03-12     1
2026-03-10     1
2026-03-18     1
2026-03-17     1
2026-03-13     1
2026-03-23     1
2026-03-24     1
2026-03-31     1
2026-04-01     1
2026-04-02     1
dtype: int64

-->> Nur mit zugeorndeten Tournummern weiter arbeiten !

In [238]:
df_ist_merged

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Meldungsquelle,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 05:19:13,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:00:13,0,0,316550.025,0.0,0.0,"53,66757","9,9928","DE - 22419 Hamburg (Langenhorn), Essener Straß...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:33:59,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-24 07:34:00,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-24 07:54:21,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",SPEDION App,OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 11:49:13,208,0,502860.415,0.0,0.0,"53,51717","9,96982","DE - 20457 Hamburg (Hamburg-Mitte), Köhlbrandb...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2871,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 11:59:39,0,0,502863.510,0.0,0.0,"53,52261","9,98925","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2872,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 12:11:29,0,0,502863.755,0.0,0.0,"53,5228","9,98903","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2873,8180.0,"Krüger, Alexander",1650,Ankunft Kunde,2026-03-06 12:37:22,0,0,502869.170,0.0,0.0,"53,5341","9,98237","DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 32",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432
2874,8180.0,"Krüger, Alexander",1651,Abfahrt Kunde,2026-03-06 13:04:35,0,0,502874.385,0.0,0.0,"53,52344","9,98587","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",SPEDION App,TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432